name: Build and deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install Composer dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        php_version: 8.1
    - name: Build assets and translation files
      run: |
        npm ci
        npm run build
        composer global config --no-plugins allow-plugins.wpify/scoper true
        composer global require wpify/scoper
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE/vendor
        composer install --no-dev --optimize-autoloader

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: truelayer-for-woocommerce
